[package]
name = "gtk_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
v8 = "0.81.0"
log = "0.4"
env_logger = "0.11.1"
